### ISSUE TITLE
Crash when moving widgets including polyline

### ISSUE THREAD

**Issue by tashasummers** [ControlSystemStudio/cs-studio#1564] opened 2016-01-14 18:27 UTC
I can move the polyline on its own. If I try to move a group of widgets that includes a polyline CS-Studio crashes. Running 4.1.5 on debian linux.

**Comment by shroffk** [comment] 2016-01-14 21:10
These problems are seen on debain using gtk2
These have been reported to have been resolved in eclipse rcp 4.5 (cs-studio product 4.2)

**Comment by berryma4** [comment] 2016-01-14 21:10
I can't reproduce this on 4.2.x.  This may have been fixed in 4.5 eclipse.

**Comment by berryma4** [comment] 2016-01-26 14:47
Can we close this, since it is fixed in 4.2.x?

**Comment by berryma4** [comment] 2016-01-26 14:51
I made a note on the Known bugs page:
https://github.com/ControlSystemStudio/cs-studio/wiki/Compatibility

**Closed** 2016-02-11 13:59 UTC
