### ISSUE TITLE
BOY: Connection between linking container

### ISSUE THREAD

**Issue by ayemos** [ControlSystemStudio/cs-studio#804] opened 2014-11-06 12:15 UTC
Hello, I'm Yuichiro Someya currently working in Cosylab d.d. as an internship student.

There's one issue reported about BOY especially with LinkingContainer widget.

The issue is like that:
I create the connector and it is visible in editor mode, but it isn't saved by XMLUtil so at runtime and at the time I reopen it, it is not visible. 

The problem can be reproduced in latest version of CS-Studio General product(4.0.3) by create connection between 
- a widget outside LinkingContainer and one inside LinkingContainer
- or two widgets inside LinkingContainer
and so on.

Maybe there's way to do workaround to the issue but I haven't grasped whole concept of CSS so still not sure how necessary it is to make it possible to create connector between them.

Furthermore, as I was trying to trace the cause, I found this issue opened before
https://github.com/ControlSystemStudio/cs-studio/issues/85
It's not urgent because I'm doing it in both self educational purpose and contribution, 
so it seems to be better to just left it aside than making many workarounds.

How do you think? Hope to hear you.

Best,
Yuichiro

**Comment by kasemir** [comment] 2015-06-08 12:53
Closing as duplicate of #912

**Closed by kasemir** 2015-06-08 12:53 UTC
