### ISSUE TITLE
Connection from Linking container

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/cs-studio#1103] opened 2015-05-06 14:06 UTC
The modification to the linking container made in the master branch there seem to be significant error with handling connections.

I have attached opi screens to re create some of the problems.
https://github.com/ControlSystemStudio/opi-regression-tests/tree/master/Issues/Issue_1103

1. The linking container + simplepv.PVManagerPV is leaking references to pv readers and writers
Open the Datasource debugger (CS-Studio --> debugging --> Datasources)
Run the Parent_connection_simple_loc.opi a couple of time, you will notice that the number of (T)otal number of listeners does not return to 0 when all opi screen are closed and no loner in the run mode.

2a. Readers are not correctly attached and Events are lost
Run the Parent_connection_simple_loc.opi, some of the text update widgets will have the correctly initialized value 0, refreshing the opi will show that some text update widgets will randomly render the correct value. 

2b. Attempts are made to write to PV's before the are created.
```
2015-05-06 10:17:55.415 WARNING [Thread 61] org.csstudio.simplepv.pvmanager.PVManagerPV (stop) - PV loc://SR_C25(0) has already been stopped or was not started yet.
2015-05-06 10:17:55.419 WARNING [Thread 61] org.csstudio.simplepv.pvmanager.PVManagerPV (stop) - PV loc://SR_C25 has already been stopped or was not started yet.
```

**Comment by kasemir** [comment] 2015-05-06 15:18
Likely caused by #912: Linking container is broken, requiring additional `if (widget instance of LinkingContainer)` type checks when starting/stopping PVs for all widgets.

**Comment by jbobnar** [comment] 2015-05-28 11:13
2a and 2b are bugs in PVManager and PVManagerPV. They are not limited to the LinkingContainer. They are visible also if you use the child opi directly, just less frequently. Hit the refresh button like crazy and you're bound to see it happen.

2b was partially fixed by #1167. The org.csstudio.simplepv.pvmanager has incorrect "synchronization" of start/stop methods. From the git comments I see some deadlocks were being fixed this way, so I do not dare to change this. But here are my thoughts:
- PVManager#start and PVManager#stop should be synchronized, because they are not thread safe. There is a (small) window when both methods could be executed synchronously. Luckily they are always called from the same thread, so a problem like that cannot happen.
- Shouldn't the stop method return after it puts a "stopping" runnable on the notification thread?
- If the notification thread is not a single thread executor, strange things might happen.

Further problem can be found in the LocalDataSource, when zeroInitialization is set to true. No matter what is set as the initial value of the PV (in BOY), the value will be parsed to java.lang.Double (inside the "initialize(String)" method). A few lines later the initial value on the channel is set to 0 (that is an integer). Integer 0 is not equal to Double 0, and exception will be thrown by the LocalChannelHandler.

The lost events problem seems to be somewhere deep in the pv manager. Open PVManagerPV and put a System.out.println(event) into the pvChanged method of the pvReaderListener. You will see that most of the times the event is [ CONN | VAL ] but sometimes the VAL is missing.

**Comment by shroffk** [comment] 2015-06-02 20:44
I agree, after looking into this a bit the connection problems 2a and 2b seem to be in the pvmanager domain.
I think we should revisit the 2a and 2b after #1174 is resolved.

**Comment by berryma4** [comment] 2015-06-23 19:05
Just a note, there are a lot of comments on the pull request.

**Comment by berryma4** [comment] 2015-06-23 19:07
In the end, i removed the connections part for inside to outside a container.
And, I removed the processVersionDifference for the LinkingContainerModel.

**Closed** 2015-06-30 12:52 UTC
Labels: BOY, bug
